# Generated by Django 4.0.4 on 2022-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(editable=False)),
                ('ship_date', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
