# Generated by Django 4.0.4 on 2022-05-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shipment_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
